apiVersion: apps/v1
kind: Deployment
metadata:
  name: okkgf05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okkgf05
  template:
    metadata:
      labels:
        app: okkgf05
    spec:
      containers:
      - image: okteto.dev/okkgf05:latest
        name: okkgf05
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/LandingStartups-html.zip"
        - name: Vless_UUID
          value: "db7ab2cf-de42-43fe-9f75-f2b3e66b724b"
        - name: Vless_Path
          value: "/hfdgjsgsfgdgfhgsfd"
        - name: Vmess_UUID
          value: "db7ab2cf-de42-43fe-9f75-f2b3e66b724b"
        - name: Vmess_Path
          value: "/gsfhdgjgsdg"
        - name: Share_Path
          value: "/v2link"
