apiVersion: v1
kind: Service
metadata:
  name: okkgf05
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "okkgf05"
    port: 8080
  selector:
    app: okkgf05
